version: "3"
  
volumes:
  nextcloud:
    driver: local
  db:

services:
  db:
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --innodb-read-only-compressed=OFF
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<INSERT-A-DATABASE-ROOT-PASSWORD>
      - MYSQL_PASSWORD=<INSERT-ANOTHER-PASSWORD-THEN-THE-DATABASE-ROOT-PASSWORD-FOR-BETTER-SECURITY>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:latest
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=<INSERT-ANOTHER-PASSWORD-THEN-THE-DATABASE-ROOT-PASSWORD-FOR-BETTER-SECURITY>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

